### ISSUE TITLE
Unable to compile it statically. 

### ISSUE THREAD

**Issue by francisreader** [hduong85/arm_adb#10]
The libs can be compiled statically, but the final binary always ends up dyn linked to glibc.

**Comment by qhuyduong** [comment]
Yeah that's true @francisreader . Statically linked glibc to final binary may result in a huge binary file. Do you have any issue with dynamic linked glibc?

**Comment by mattiasbe** [comment]
Yes old glibc on target that would like to use adb with a connected device :)

**Comment by mattiasbe** [comment]
`~/arm_adb$ nano src/Makefile.in`
Change:
`adb_LDFLAGS = -static -L$(libdir)`
to:
`adb_LDFLAGS = -static -L$(libdir) -static-libgcc -static-libstdc++`
