### ISSUE TITLE
Is it possible to build newest arm-adb from master branch ?

### ISSUE THREAD

**Issue by andrewleo** [hduong85/arm_adb#11]
![snip20180914_129](https://user-images.githubusercontent.com/3241895/45527430-166b8c00-b80e-11e8-80aa-ed8bc6ec1f81.png)
Is it possible to build newest arm-adb from master branch ? maybe the version 1.0.40?
Seems it will improve the stable of adb connection

**Comment by qhuyduong** [comment]
Sure I planned to do it but too busy so far. I will try to finish it soon 😄

**Comment by andrewleo** [comment]
Much thanks for your help.
Waiting for good news!

**Comment by codeskyblue** [comment]
+1 waiting...

**Comment by qhuyduong** [comment]
Hi @andrewleo @codeskyblue ,
I have just made a test build for adb v1.0.40 for armv7.
Could you guys please help to test this binary? If it works well I will commit the code.
[adb_v1.0.40_armv7.zip](https://github.com/qhuyduong/arm_adb/files/2406162/adb_v1.0.40_armv7.zip)
Best regards,
Huy Duong

**Comment by qhuyduong** [comment]
Please use this one 
[adb_v1.0.40.2_armv7.zip](https://github.com/qhuyduong/arm_adb/files/2407645/adb_v1.0.40.2_armv7.zip)

**Comment by codeskyblue** [comment]
Hi @qhuyduong, use 1.0.40.2
It shows that

```bash
pi@RPi-XY:~ $ ./adb devices
./adb: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./adb)
./adb: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./adb)
pi@RPi-XY:~ $ ldd --version
ldd (Debian GLIBC 2.19-18+deb8u7) 2.19
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

pi@RPi-XY:/usr/lib/arm-linux-gnueabihf $ strings libstdc++.so.6 |grep CXXABI
CXXABI_1.3
CXXABI_1.3.1
CXXABI_1.3.2
CXXABI_1.3.3
CXXABI_1.3.4
CXXABI_1.3.5
CXXABI_1.3.6
CXXABI_1.3.7
CXXABI_1.3.8
CXXABI_TM_1
CXXABI_ARM_1.3.3
```

**Comment by andrewleo** [comment]
`adb devices` return then same as @codeskyblue 

But when I run the `strings` command, there is no  <strong>1.3.9 version</strong>:
```
root@raspberrypi-4:/usr/lib/arm-linux-gnueabihf# strings libstdc++.so.6 |grep CXXABI
CXXABI_1.3
CXXABI_1.3.1
CXXABI_1.3.2
CXXABI_1.3.3
CXXABI_1.3.4
CXXABI_1.3.5
CXXABI_1.3.6
CXXABI_1.3.7
CXXABI_1.3.8
CXXABI_TM_1
CXXABI_ARM_1.3.3
```

I will try to resolve this on google, maybe gcc problems or others.
Do you have some other suggestions? The adb binary works well on your Raspbian?

**Comment by qhuyduong** [comment]
@andrewleo it works well on latest Raspbian Stretch so this should be the gcc problem. You can update gcc to a newer version or re-compile yourself on your Raspberry:

1. Clone and build boringssl:
```
$ git clone https://github.com/qhuyduong/boringssl.git
$ cd boringssl
$ mkdir build && cd build
$ cmake -DCMAKE_ARCHIVE_OUTPUT_DIRECTORY=/tmp/openssl ../
$ make
$ make install
```
2. Clone and build arm_adb:
```
$ git clone https://github.com/qhuyduong/arm_adb -b v1.0.40
$ cd arm_adb
$ ./configure --includedir=/tmp/openssl/include --libdir=/tmp/openssl
$ make
```

**Comment by andrewleo** [comment]
ok, I will try compile myself as soon as possible, much thanks!

**Comment by brantxiong** [comment]
@qhuyduong It's possible to do cross-compile to arm_adb v1.0.40?  If possible, which toolchain should I use in command: `os/compiler:$TOOLCHAIN_PREFIX-gcc`?

**Comment by andrewleo** [comment]
I have already build **_arm-adb based on the jessie version_**, and will test the stability soon. 
Much thanks!

**Comment by luoyesiqiu** [comment]
@qhuyduong You saved my life！
