### ISSUE TITLE
在树莓派上最多识别6台手机吗？

### ISSUE THREAD

**Issue by nateby** [hduong85/arm_adb#12]
您好，我下载了之后尝试在树莓派3B+上使用，raspbian的系统

使用工业级hub，当连接6台手机设备的时候正常使用，而且操作不会卡

但是当连接第7台手机的时候，树莓派CPU的%wait就会突然升高，达到50%左右
我通过iotop查看，发现是kworker的IO特别高，达到99%，但是实际上是没有IO读写产生的
然后就会导致7台手机都特别的卡

查了很多资料不清楚是什么导致的
请教下，有没有可能是adb产生的问题？

谢谢

**Comment by qhuyduong** [comment]
@nateby Could you please try this ?
[adb_v1.0.40_armv7_libusb.zip](https://github.com/qhuyduong/arm_adb/files/2407789/adb_v1.0.40_armv7_libusb.zip)

In the previous function, I disabled the libusb and used native usb code instead. 
Now I try re-enable it. Hope it helps.

P/s: Please use English next time. I couldn't understand Chinese 🤦‍♂️

**Comment by nateby** [comment]
thank you
I will try it on RaspberryPI 3B+
thanks again
