### ISSUE TITLE
[Question]Run and arm_adv from android using terminal emulator?

### ISSUE THREAD

**Issue by gmkbenjamin** [hduong85/arm_adb#13]
Hello,
Just wondering if it's possible to run this on an android device using terminal emulator? I tried run it but got permission denied error. chmod +x didn't help either.

Thank you.

**Comment by qhuyduong** [comment]
@gmkbenjamin No it's not possible. The main reason is that this package relies GLIBC which is not available on android.

**Comment by gmkbenjamin** [comment]
Ah right. That makes sense. Thank you. I will try termux and chroot/proot linux.
