### ISSUE TITLE
Can I implement it by modifying android.mk?

### ISSUE THREAD

**Issue by applehub** [hduong85/arm_adb#3]
Can I implement it by modifying android.mk? I really need your help

I wanted to compile the ARM-Linux ADB, but there was no tool chain. Or the tool chain could not be used, and then I compiled it, but linker was wrong, so I created the directory/system/bin/linker and /system/lib

**Comment by qhuyduong** [comment]
Sorry but I didn't quite get your problem.
What's the issue so far?
If you follow my guideline closely, you can compile yourself a binary for ARM without any modification.
Or you find a prebuilt one in the release if you have problem with compilation: https://github.com/hduong85/arm_adb/releases

Thanks.

**Comment by applehub** [comment]
My compiler environment is x86_64-Ubuntu 14.04.5 LTS ,runtime environment is armv7l-32bit-Ubuntu 16.04 LTS,The main difference is the architecture .
Compile the arm version by modifying the  "/system/core/adb/android.mk ",This is my current method .
succeed!!! but the adb  executable file like this:

**Comment by applehub** [comment]
![1](https://user-images.githubusercontent.com/30278353/33015101-85fb5c32-ce24-11e7-9512-5d512e6ef905.jpg)

**Comment by applehub** [comment]
But I want to solve the link problem by modifying theThe file under the three three directory:

build\core\combo
\bionic\linker
\external\clang\lib\Driver

trying many times failed, I come from China, my English is not good, thank you for your help.
