### ISSUE TITLE
How can I build for arm and use as HOST

### ISSUE THREAD

**Issue by JamesChungZLL** [hduong85/arm_adb#5]
I hava a raperbarry PI3, want a custom adb for it, and use PI3 as a host.

Follow your step, successfully build adb, then use "adb devices" cannot find the Android devices. And I see the adb command use the socket port 5038.

Then I tried to delete "-DADB_HOST_ON_TARGET=1" in "Makefile.am" & "Makefile.in", also successfully build, and also "adb devices" can not find the Android devices.

**Comment by qhuyduong** [comment]
Hi. Please try to:
1. Clean the build folder
2. Delete "-DADB_HOST_ON_TARGET=1" in "Makefile.am" (don't need to modify Makefile.in)
3. Run "autoreconf -i --force"
4. Configure and make again.

**Comment by JamesChungZLL** [comment]
OK, Follow your steps, and done.
Thanks!
