### ISSUE TITLE
libstdc++ warning on ARMv7 build

### ISSUE THREAD

**Issue by fhemberger** [hduong85/arm_adb#8]
Running the provided `adb` build on ARMv7 gives me the following warning several times:

```
/lib/libstdc++.so.6: no version information available (required by adb)
```

**Comment by qhuyduong** [comment]
Hi @fhemberger ,

This warning means that the shared libraries on your machine don't match with the ones used to build the provided adb. You can rebuild the source yourself to eliminate the warning.

Thanks.
