### ISSUE TITLE
How to 5037 instead of default port 5038

### ISSUE THREAD

**Issue by nateby** [hduong85/arm_adb#9]
Is any reason for 5038 as default port?
And I want to use 5037 as default port,Can you provide the step?
Thanks for your help.

**Comment by qhuyduong** [comment]
Hi @nateby ,

The reason for choosing 5038 is explained within adb.h

```
#if ADB_HOST_ON_TARGET
/* adb and adbd are coexisting on the target, so use 5038 for adb
 * to avoid conflicting with adbd's usage of 5037
 */
#  define DEFAULT_ADB_PORT 5038
#else
#  define DEFAULT_ADB_PORT 5037
#endif
```
To change the default port to 5037, please try:
1. Clean the build folder
2. Delete "-DADB_HOST_ON_TARGET=1" in "src/Makefile.am" (don't need to modify Makefile.in)
3. Run "autoreconf -i --force"
4. Configure and make again.

Thanks.

**Comment by nateby** [comment]
thanks for that
